# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKlkpvMrZYNHI-0pfC77mlsL8T4CDlVL
"""

# streamlit_app.py
import streamlit as st
import joblib
import pandas as pd

# Load the trained model
model = joblib.load('delivery_time_model.pkl')

# Title
st.title("🚚 Timelytics - Delivery Time Prediction")

# Input fields
product_category = st.selectbox("Product Category", ['Electronics', 'Clothing', 'Furniture', 'Toys', 'Books'])
customer_location = st.selectbox("Customer Location", ['New York', 'California', 'Texas', 'Florida', 'Washington'])
shipping_method = st.selectbox("Shipping Method", ['Standard', 'Expedited', 'Overnight'])

# Prediction
if st.button("Predict Delivery Time"):
    input_data = pd.DataFrame({
        'product_category': [product_category],
        'customer_location': [customer_location],
        'shipping_method': [shipping_method]
    })
    delivery_time = model.predict(input_data)[0]
    st.success(f"✅ Predicted Delivery Time: {delivery_time:.2f} days")

